version: 1

gateway:
  name: "iotgw-rpi4"
  timezone: "Europe/Paris"
  loglevel: "info"
  logfile: "/var/log/iotgw.log"
  metrics_port: 9100

# Les fragments de protocole à inclure
includes:

# Connecteurs supplémentaires directement dans le master
connectors:
  spi_dev0:
    type: spi
    params:
      device: /dev/spidev0.0
      mode: 0
      bits_per_word: 8
      speed_hz: 1000000
      # <-- THIS is the important part:
      transactions:
        - op: transfer   # write+read in one segment
          len: 2
          tx: "0xA55A"   # bytes sent: A5 5A
          rx_len: 2      # bytes read back

  mqtt_local:
    type: mqtt
    params:
      host: "127.0.0.1"
      port: 1883

bridges:
  spi_to_mqtt_demo:
    from: spi_dev0
    to: mqtt_local
