version: 1

gateway:
  name: "iotgw-rpi4"
  timezone: "Europe/Paris"
  loglevel: "info"
  logfile: "/var/log/iotgw.log"
  metrics_port: 9100

# Les fragments de protocole à inclure
includes:
  - protocols/mqtt.yaml
  - protocols/http_server.yaml

# Connecteurs supplémentaires directement dans le master
connectors:
  # Exemple direct (en plus des includes)
  local_http:
    type: http-server
    params:
      bind: "0.0.0.0:8081"

# Routes (bridges) entre connecteurs

bridges:
  http_to_mqtt_demo:
    from: local_http
    to: mqtt_local
