version: 1

gateway:
  name: "gw01"
  timezone: "UTC"
  loglevel: "info"
  logfile: "/var/log/iotgwd.log"

connectors:
  mqtt_cloud:
    type: mqtt
    url: "tcp://broker.example.com:1883"
    client_id: "gw01"
    tls: false
    pub_topic: "gw01/out/#"
    sub_topic: "gw01/in/#"

  modbus_rtu_sensor:
    type: modbus-rtu
    device: "/dev/ttyUSB0"
    baudrate: 115200
    parity: "N"
    stop_bits: 1
    slave_id: 1
    registers:
      temp_c:   {addr: 40001, type: uint16, scale: 0.1}
      pressure: {addr: 40002, type: uint16, scale: 0.01}

  modbus_tcp_plc:
    type: modbus-tcp
    host: "192.168.10.50"
    port: 502
    unit_id: 1

  canopen_motor:
    type: canopen
    iface: "can0"
    bitrate: 500000
    node_id: 3

bridges:
  sensor_to_cloud:
    from: modbus_rtu_sensor
    to:   mqtt_cloud
    mode: poll
    period: "1s"
    # tableau de couples src/dst
    mapping:
      - [ temp_c  , factory/temperature ]
      - [ pressure, factory/pressure   ]

  plc_to_motor:
    from: modbus_tcp_plc
    to:   canopen_motor
    mode: subscribe
    mapping:
      - [ holding_41001, rpm_target ]

