name: Config Validation

on:
  push:
    paths:
      - "meta-iotgw/recipes-iotgw/iotgwd/files/**"
      - "scripts/validate_cfg.py"
      - "tests/**"
      - "requirements.txt"
  pull_request:
    paths:
      - "meta-iotgw/recipes-iotgw/iotgwd/files/**"
      - "scripts/validate_cfg.py"
      - "tests/**"
      - "requirements.txt"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (sparse)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          filter: blob:none
          sparse-checkout: |
            scripts/validate_cfg.py
            meta-iotgw/recipes-iotgw/iotgwd/files/
            tests/
            requirements.txt
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest -q
