name: Config Validation

on:
  push:
    paths:
      - "meta-iotgw/recipes-iotgw/iotgwd/files/config.example.yaml"
      - "meta-iotgw/recipes-iotgw/iotgwd/files/iotgw.schema.json"
  pull_request:
    paths:
      - "meta-iotgw/recipes-iotgw/iotgwd/files/config.example.yaml"
      - "meta-iotgw/recipes-iotgw/iotgwd/files/iotgw.schema.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Create venv & install deps
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Validate example config with validate_cfg.py
        shell: bash
        run: |
          source .venv/bin/activate
          pytest -q
